#запускает локальный pgadmin4
services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "127.0.0.1:5050:80"
    volumes:
      - ./volumes/pgadmin4:/var/lib/pgadmin
    restart: unless-stopped