version: '3.8'
services:
  dind-jenkins:
    container_name: dind-jenkins
    build: .
    image: dind-jenkins:java21
    privileged: true
    restart: always
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-volume:/root/.jenkins
      - ~/.ssh:/root/.ssh  # Пробрасываем SSH-ключи
      - ~/.gitconfig:/root/.gitconfig  # Пробрасываем глобальные настройки Git
    networks:
      - dind-jenkins-network


networks:
  dind-jenkins-network:
    driver: bridge
