services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
        DOCKER_GROUP_ID: 984
    image: local-jenkins:java21
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-volume:/home/petr/.jenkins
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/petr/.ssh:/home/petr/.ssh
      - /home/petr/.gitconfig:/home/petr/.gitconfig:ro
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
